name: Update package

on:
  workflow_dispatch:

jobs:
  copy_file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      
    - name: Get current git tag
      id: tag
      uses: JinoArch/get-latest-tag@latest

    - name: Copy files to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.1
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: LICENSE README.md ansi_render.typ typst.toml
        destination-username: 8LWXpg
        destination-repository: packages
        destination-branch: main
        destination-directory: /preview/ansi-render:${{ steps.tag.outputs.tag }}
        commit-email: v3ak6xhthk@gmail.com
        commit-message: anis-render:${{ steps.tag.outputs.tag }}
